<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>FutureIoan测试报告</title>
    <meta name="generator" content="HTMLTestRunner 0.8.2.2"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    
<style type="text/css" media="screen">
body        { font-family: Microsoft YaHei,Tahoma,arial,helvetica,sans-serif;padding: 20px; font-size: 120%; }
table       { font-size: 100%; }
/* -- heading ---------------------------------------------------------------------- */
.heading {
    margin-top: 0ex;
    margin-bottom: 1ex;
}
.heading .description {
    margin-top: 4ex;
    margin-bottom: 6ex;
}
/* -- report ------------------------------------------------------------------------ */
#total_row  { font-weight: bold; }
.passCase   { color: #5cb85c; }
.failCase   { color: #d9534f; font-weight: bold; }
.errorCase  { color: #f0ad4e; font-weight: bold; }
.hiddenRow  { display: none; }
.testcase   { margin-left: 2em; }
</style>

</head>
<body >
<script language="javascript" type="text/javascript">
output_list = Array();
/*level 调整增加只显示通过用例的分类 --Findyou
0:Summary //all hiddenRow
1:Failed  //pt hiddenRow, ft none
2:Pass    //pt none, ft hiddenRow
3:All     //pt none, ft none
*/
function showCase(level) {
    trs = document.getElementsByTagName("tr");
    for (var i = 0; i < trs.length; i++) {
        tr = trs[i];
        id = tr.id;
        if (id.substr(0,2) == 'ft') {
            if (level == 2 || level == 0 ) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
        if (id.substr(0,2) == 'pt') {
            if (level < 2) {
                tr.className = 'hiddenRow';
            }
            else {
                tr.className = '';
            }
        }
    }
    //加入【详细】切换文字变化 --Findyou
    detail_class=document.getElementsByClassName('detail');
	//console.log(detail_class.length)
	if (level == 3) {
		for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="收起"
		}
	}
	else{
			for (var i = 0; i < detail_class.length; i++){
			detail_class[i].innerHTML="详细"
		}
	}
}
function showClassDetail(cid, count) {
    var id_list = Array(count);
    var toHide = 1;
    for (var i = 0; i < count; i++) {
        //ID修改 点 为 下划线 -Findyou
        tid0 = 't' + cid.substr(1) + '_' + (i+1);
        tid = 'f' + tid0;
        tr = document.getElementById(tid);
        if (!tr) {
            tid = 'p' + tid0;
            tr = document.getElementById(tid);
        }
        id_list[i] = tid;
        if (tr.className) {
            toHide = 0;
        }
    }
    for (var i = 0; i < count; i++) {
        tid = id_list[i];
        //修改点击无法收起的BUG，加入【详细】切换文字变化 --Findyou
        if (toHide) {
            document.getElementById(tid).className = 'hiddenRow';
            document.getElementById(cid).innerText = "详细"
        }
        else {
            document.getElementById(tid).className = '';
            document.getElementById(cid).innerText = "收起"
        }
    }
}
function html_escape(s) {
    s = s.replace(/&/g,'&amp;');
    s = s.replace(/</g,'&lt;');
    s = s.replace(/>/g,'&gt;');
    return s;
}
</script>
<div class='heading'>
<h1 style="font-family: Microsoft YaHei">FutureIoan测试报告</h1>
<p class='attribute'><strong>测试人员 : </strong> zr</p>
<p class='attribute'><strong>开始时间 : </strong> 2019-04-09 20:34:10</p>
<p class='attribute'><strong>合计耗时 : </strong> 0:00:23.542000</p>
<p class='attribute'><strong>测试结果 : </strong> 共 22，错误 22，通过率= 0.00%</p>

<p class='description'>login</p>
</div>


<p id='show_detail_line'>
<a class="btn btn-primary" href='javascript:showCase(0)'>概要{ 0.00% }</a>
<a class="btn btn-danger" href='javascript:showCase(1)'>失败{ 0 }</a>
<a class="btn btn-success" href='javascript:showCase(2)'>通过{ 0 }</a>
<a class="btn btn-info" href='javascript:showCase(3)'>所有{ 22 }</a>
</p>
<table id='result_table' class="table table-condensed table-bordered table-hover">
<colgroup>
<col align='left' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
<col align='right' />
</colgroup>
<tr id='header_row' class="text-center success" style="font-weight: bold;font-size: 16px;">
    <td>用例集/测试用例</td>
    <td>总计</td>
    <td>通过</td>
    <td>失败</td>
    <td>错误</td>
    <td>详细</td>
</tr>

<tr class='errorClass warning'>
    <td>future_3.test_cases.register_cases.Register</td>
    <td class="text-center">10</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">10</td>
    <td class="text-center"><a href="javascript:showClassDetail('c1',10)" class="detail" id='c1'>详细</a></td>
</tr>

<tr id='ft1_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_01: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_1'>错误</button>
    <div id='div_ft1_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_1'>错误</button>
    <div id='div_ft1_1' class="collapse in" align="left">
    <pre>
    
ft1_1: 2019-04-09 20:34:10,386-INFO-log_msg.py-root-34-日志信息：=====正在测试register模块里面第1条用例：正确注册
post请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000002669128&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\register_cases.py", line 34, in test_register
    resp = HttpRequest().http_request(method, url, param)
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_02: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_2'>错误</button>
    <div id='div_ft1_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_2'>错误</button>
    <div id='div_ft1_2' class="collapse in" align="left">
    <pre>
    
ft1_2: 2019-04-09 20:34:11,493-INFO-log_msg.py-root-34-日志信息：=====正在测试register模块里面第2条用例：错误的手机号
post请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003F0F0B8&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\register_cases.py", line 34, in test_register
    resp = HttpRequest().http_request(method, url, param)
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_03: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_3'>错误</button>
    <div id='div_ft1_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_3'>错误</button>
    <div id='div_ft1_3' class="collapse in" align="left">
    <pre>
    
ft1_3: 2019-04-09 20:34:12,589-INFO-log_msg.py-root-34-日志信息：=====正在测试register模块里面第3条用例：错误的密码
post请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003EA69B0&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\register_cases.py", line 34, in test_register
    resp = HttpRequest().http_request(method, url, param)
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_04: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_4'>错误</button>
    <div id='div_ft1_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_4'>错误</button>
    <div id='div_ft1_4' class="collapse in" align="left">
    <pre>
    
ft1_4: 2019-04-09 20:34:13,695-INFO-log_msg.py-root-34-日志信息：=====正在测试register模块里面第4条用例：已注册的手机号
post请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003EDAA20&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\register_cases.py", line 34, in test_register
    resp = HttpRequest().http_request(method, url, param)
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_05: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_5'>错误</button>
    <div id='div_ft1_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_5'>错误</button>
    <div id='div_ft1_5' class="collapse in" align="left">
    <pre>
    
ft1_5: 2019-04-09 20:34:14,801-INFO-log_msg.py-root-34-日志信息：=====正在测试register模块里面第5条用例：手机号为空
post请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/register (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003F21F60&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\register_cases.py", line 34, in test_register
    resp = HttpRequest().http_request(method, url, param)
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_06: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_6'>错误</button>
    <div id='div_ft1_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_6'>错误</button>
    <div id='div_ft1_6' class="collapse in" align="left">
    <pre>
    
ft1_6: 2019-04-09 20:34:15,901-INFO-log_msg.py-root-34-日志信息：=====正在测试login模块里面第6条用例：正确登录
get请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/login?pwd=123456&amp;mobilephone=13321345684 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003F0B828&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\register_cases.py", line 34, in test_register
    resp = HttpRequest().http_request(method, url, param)
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_7' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_07: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_7'>错误</button>
    <div id='div_ft1_7' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_7' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_7'>错误</button>
    <div id='div_ft1_7' class="collapse in" align="left">
    <pre>
    
ft1_7: 2019-04-09 20:34:17,002-INFO-log_msg.py-root-34-日志信息：=====正在测试login模块里面第7条用例：错误的用户名
get请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/login?pwd=123456&amp;mobilephone=133 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003F18438&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\register_cases.py", line 34, in test_register
    resp = HttpRequest().http_request(method, url, param)
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_8' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_08: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_8'>错误</button>
    <div id='div_ft1_8' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_8' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_8'>错误</button>
    <div id='div_ft1_8' class="collapse in" align="left">
    <pre>
    
ft1_8: 2019-04-09 20:34:18,097-INFO-log_msg.py-root-34-日志信息：=====正在测试login模块里面第8条用例：错误的密码
get请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/login?pwd=1234&amp;mobilephone=13387654333 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003F0BBA8&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\register_cases.py", line 34, in test_register
    resp = HttpRequest().http_request(method, url, param)
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_9' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_09: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_9' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_9'>错误</button>
    <div id='div_ft1_9' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_9' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_9'>错误</button>
    <div id='div_ft1_9' class="collapse in" align="left">
    <pre>
    
ft1_9: 2019-04-09 20:34:19,198-INFO-log_msg.py-root-34-日志信息：=====正在测试login模块里面第9条用例：空密码
get请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/login?pwd=&amp;mobilephone=13387654321 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003F0F240&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\register_cases.py", line 34, in test_register
    resp = HttpRequest().http_request(method, url, param)
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft1_10' class='none'>
    <td class='errorCase'><div class='testcase'>test_register_10: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft1_10' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft1_10'>错误</button>
    <div id='div_ft1_10' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft1_10' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft1_10'>错误</button>
    <div id='div_ft1_10' class="collapse in" align="left">
    <pre>
    
ft1_10: 2019-04-09 20:34:20,287-INFO-log_msg.py-root-34-日志信息：=====正在测试login模块里面第10条用例：空用户名
get请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/login?pwd=123456&amp;mobilephone= (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003F18278&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\register_cases.py", line 34, in test_register
    resp = HttpRequest().http_request(method, url, param)
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>future_3.test_cases.recharge_cases.Recharge</td>
    <td class="text-center">6</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">6</td>
    <td class="text-center"><a href="javascript:showClassDetail('c2',6)" class="detail" id='c2'>详细</a></td>
</tr>

<tr id='ft2_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_recharge_1: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_1'>错误</button>
    <div id='div_ft2_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_1'>错误</button>
    <div id='div_ft2_1' class="collapse in" align="left">
    <pre>
    
ft2_1: 2019-04-09 20:34:21,389-INFO-log_msg.py-root-34-日志信息：=====正在测试recharge模块里面第1条用例：未登录充值
get请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/recharge?amount=100&amp;mobilephone=13387654333 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003EDF470&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\recharge_cases.py", line 40, in test_recharge
    resp = HttpRequest().http_request(method, url, param,getattr(GetData,'COOKIE'))
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_recharge_2: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_2'>错误</button>
    <div id='div_ft2_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_2'>错误</button>
    <div id='div_ft2_2' class="collapse in" align="left">
    <pre>
    
ft2_2: 2019-04-09 20:34:22,492-INFO-log_msg.py-root-34-日志信息：=====正在测试login模块里面第2条用例：登录
get请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/login?pwd=123456&amp;mobilephone=13387654333 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003F1B908&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\recharge_cases.py", line 40, in test_recharge
    resp = HttpRequest().http_request(method, url, param,getattr(GetData,'COOKIE'))
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_recharge_3: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_3'>错误</button>
    <div id='div_ft2_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_3'>错误</button>
    <div id='div_ft2_3' class="collapse in" align="left">
    <pre>
    
ft2_3: 2019-04-09 20:34:23,590-INFO-log_msg.py-root-34-日志信息：=====正在测试recharge模块里面第3条用例：登录充值
get请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/recharge?amount=100&amp;mobilephone=13387654333 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003F182E8&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\recharge_cases.py", line 40, in test_recharge
    resp = HttpRequest().http_request(method, url, param,getattr(GetData,'COOKIE'))
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_4' class='none'>
    <td class='errorCase'><div class='testcase'>test_recharge_4: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_4'>错误</button>
    <div id='div_ft2_4' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_4' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_4'>错误</button>
    <div id='div_ft2_4' class="collapse in" align="left">
    <pre>
    
ft2_4: 2019-04-09 20:34:24,900-INFO-log_msg.py-root-34-日志信息：=====正在测试recharge模块里面第4条用例：充值账号为空
get请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/recharge?amount=100&amp;mobilephone= (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003F0B3C8&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\recharge_cases.py", line 40, in test_recharge
    resp = HttpRequest().http_request(method, url, param,getattr(GetData,'COOKIE'))
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_5' class='none'>
    <td class='errorCase'><div class='testcase'>test_recharge_5: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_5' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_5'>错误</button>
    <div id='div_ft2_5' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_5' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_5'>错误</button>
    <div id='div_ft2_5' class="collapse in" align="left">
    <pre>
    
ft2_5: 2019-04-09 20:34:26,005-INFO-log_msg.py-root-34-日志信息：=====正在测试recharge模块里面第5条用例：充值金额为空
get请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/recharge?amount=&amp;mobilephone=13387654333 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003F1B7B8&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\recharge_cases.py", line 40, in test_recharge
    resp = HttpRequest().http_request(method, url, param,getattr(GetData,'COOKIE'))
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft2_6' class='none'>
    <td class='errorCase'><div class='testcase'>test_recharge_6: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft2_6' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft2_6'>错误</button>
    <div id='div_ft2_6' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft2_6' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft2_6'>错误</button>
    <div id='div_ft2_6' class="collapse in" align="left">
    <pre>
    
ft2_6: 2019-04-09 20:34:27,108-INFO-log_msg.py-root-34-日志信息：=====正在测试recharge模块里面第6条用例：充值金额大于50w
get请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/recharge?amount=600000&amp;mobilephone=13387654333 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003F186D8&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\recharge_cases.py", line 40, in test_recharge
    resp = HttpRequest().http_request(method, url, param,getattr(GetData,'COOKIE'))
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>future_3.test_cases.loan_cases.Loan</td>
    <td class="text-center">3</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">3</td>
    <td class="text-center"><a href="javascript:showClassDetail('c3',3)" class="detail" id='c3'>详细</a></td>
</tr>

<tr id='ft3_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_loan_1: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_1'>错误</button>
    <div id='div_ft3_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_1'>错误</button>
    <div id='div_ft3_1' class="collapse in" align="left">
    <pre>
    
ft3_1: 2019-04-09 20:34:28,202-INFO-log_msg.py-root-34-日志信息：=====正在测试login模块里面第1条用例：正确登录
get请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/login?pwd=123456&amp;mobilephone=13387654333 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003E94A20&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\loan_cases.py", line 47, in test_loan
    resp = HttpRequest().http_request(method, url, param,getattr(GetData,'COOKIE'))
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_loan_2: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_2'>错误</button>
    <div id='div_ft3_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_2'>错误</button>
    <div id='div_ft3_2' class="collapse in" align="left">
    <pre>
    
ft3_2: 2019-04-09 20:34:29,292-INFO-log_msg.py-root-34-日志信息：=====正在测试add_loan模块里面第2条用例：加标
get请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/loan/add?amount=100000&amp;repaymemtWay=4&amp;loanTerm=6&amp;loanRate=10&amp;biddingDays=10&amp;memberId=1123539&amp;title=zr%E7%9A%84%E6%A0%87&amp;loanDateType=0 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003F1B518&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\loan_cases.py", line 47, in test_loan
    resp = HttpRequest().http_request(method, url, param,getattr(GetData,'COOKIE'))
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft3_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_loan_3: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft3_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft3_3'>错误</button>
    <div id='div_ft3_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft3_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft3_3'>错误</button>
    <div id='div_ft3_3' class="collapse in" align="left">
    <pre>
    
ft3_3: Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\loan_cases.py", line 42, in test_loan
    param = eval(get_data.replace(case['Params']))
  File ".\future_3\common\get_data.py", line 19, in replace
    value = getattr(GetData, key)
AttributeError: type object 'GetData' has no attribute 'loanid'


    </pre>
    </div>
    </td>
</tr>

<tr class='errorClass warning'>
    <td>future_3.test_cases.invest_cases.Invest</td>
    <td class="text-center">3</td>
    <td class="text-center">0</td>
    <td class="text-center">0</td>
    <td class="text-center">3</td>
    <td class="text-center"><a href="javascript:showClassDetail('c4',3)" class="detail" id='c4'>详细</a></td>
</tr>

<tr id='ft4_1' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_1: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_1' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_1'>错误</button>
    <div id='div_ft4_1' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_1' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_1'>错误</button>
    <div id='div_ft4_1' class="collapse in" align="left">
    <pre>
    
ft4_1: 2019-04-09 20:34:30,398-INFO-log_msg.py-root-34-日志信息：=====正在测试login模块里面第1条用例：正确登录
get请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/login?pwd=123456&amp;mobilephone=13387654333 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003EE9A90&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\invest_cases.py", line 46, in test_invest
    resp = HttpRequest().http_request(method, url, param, getattr(GetData, 'COOKIE'))
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_2' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_2: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_2' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_2'>错误</button>
    <div id='div_ft4_2' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_2' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_2'>错误</button>
    <div id='div_ft4_2' class="collapse in" align="left">
    <pre>
    
ft4_2: 2019-04-09 20:34:31,503-INFO-log_msg.py-root-34-日志信息：=====正在测试Invets模块里面第2条用例：正常投资
get请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/bidLoan?amount=100&amp;password=123456&amp;memberId=1123539&amp;loanId=19575 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003F18898&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\invest_cases.py", line 46, in test_invest
    resp = HttpRequest().http_request(method, url, param, getattr(GetData, 'COOKIE'))
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='ft4_3' class='none'>
    <td class='errorCase'><div class='testcase'>test_invest_3: dict() -> new empty dictionary</div></td>
    <td colspan='5' align='center'>
    <!--默认收起错误信息 -Findyou
    <button id='btn_ft4_3' type="button"  class="btn btn-danger btn-xs collapsed" data-toggle="collapse" data-target='#div_ft4_3'>错误</button>
    <div id='div_ft4_3' class="collapse">  -->
    <!-- 默认展开错误信息 -Findyou -->
    <button id='btn_ft4_3' type="button"  class="btn btn-danger btn-xs" data-toggle="collapse" data-target='#div_ft4_3'>错误</button>
    <div id='div_ft4_3' class="collapse in" align="left">
    <pre>
    
ft4_3: 2019-04-09 20:34:32,829-INFO-log_msg.py-root-34-日志信息：=====正在测试Invets模块里面第3条用例：不输入金额
get请求出错了：HTTPConnectionPool(host='47.107.168.87', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/bidLoan?amount=&amp;password=123456&amp;memberId=1123539&amp;loanId=19575 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000000003F0B898&gt;: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Traceback (most recent call last):
  File "F:\Python34\lib\site-packages\ddt.py", line 145, in wrapper
    return func(self, *args, **kwargs)
  File ".\future_3\test_cases\invest_cases.py", line 46, in test_invest
    resp = HttpRequest().http_request(method, url, param, getattr(GetData, 'COOKIE'))
  File ".\future_3\common\http_request.py", line 31, in http_request
    return resp
NameError: name 'resp' is not defined


    </pre>
    </div>
    </td>
</tr>

<tr id='total_row' class="text-center active">
    <td>总计</td>
    <td>22</td>
    <td>0</td>
    <td>0</td>
    <td>22</td>
    <td>通过率：0.00%</td>
</tr>
</table>

<div id='ending'>&nbsp;</div>
    <div style=" position:fixed;right:50px; bottom:30px; width:20px; height:20px;cursor:pointer">
    <a href="#"><span class="glyphicon glyphicon-eject" style = "font-size:30px;" aria-hidden="true">
    </span></a></div>
    
</body>
</html>
